//

import {
    ArrowLeft,
    BriefcaseBusiness,
    Building2,
    ChevronDown,
    CircleAlert,
    CircleCheck,
    CircleUser,
    CircleUserRound,
    CircleX,
    createIcons,
    Dot,
    Eye,
    Filter,
    Mail,
    MapPin,
    Package,
    Pencil,
    PenLine,
    Phone,
    Plus,
    RotateCw,
    Search,
    Trash,
    UserRound,
    UsersRound,
} from "lucide";

createIcons({
    icons: {
        Search,
        Plus,
        Eye,
        PenLine,
        CircleX,
        UsersRound,
        Pencil,
        RotateCw,
        UserRound,
        ChevronDown,
        CircleAlert,
        ArrowLeft,
        Dot,
        Trash,
        Filter,
        Mail,
        Phone,
        MapPin,
        Building2,
        Package,
        CircleCheck,
        CircleUserRound,
        CircleUser,
        BriefcaseBusiness,
    },
});
